[package]
name = "another-tracing-mcre"
version = "0.1.0"
edition = "2021"

[features]
break-tracing = ["tracing/log"]

[dependencies]
tracing = "0.1.33"
reqwest = "0.11.10"
tracing-subscriber = "0.3.11"

[dependencies.tokio]
version = "1.17.0"
features = ["rt", "macros"]